---

apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  containers:
    - name: tomcatapp
      image: sasidharsaz/vprofileapp
      ports:
        - name: vproapp-port
          containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: website
spec:
  containers:
    - name: website
      image: sasidharsaz/moso_interior
      ports:
        - name: websiteport
          containerPort: 80
