---

apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "echo $KUBERNETES_PORT && echo $MESSAGE"]
    env:
    - name: MESSAGE
      value: "hello sasi"
  restartPolicy: OnFailure
