apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      svc: nginx
  template:
    metadata:
      labels:
        svc: nginx
    spec:
      containers:
      - name: nginx-img
        image: nginx:latest
