---


apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: website
spec:
  containers:        
    - name: website
      image: sasidharsaz/moso_interior
      ports:
        - name: websiteport
          containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-website
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

